---
title: "People"
---

___
## Faculty


__Jeff Leek__ 

Jeff is a Professor of Biostatistics and Oncology at the Johns Hopkins Bloomberg School of Public Health. His research focuses on public health genomics, data science as a science, and research on the scientific literature.  He is also co-creator of the Johns Hopkins Data Science Specialization on Coursera (https://www.coursera.org/specializations/jhu-data-science) that has enrolled over 4 million. He is a co-editor of the journal Biostatistics. He writes a blog at Simply Statistics and is the author of the best-selling book "The Elements of Data Analytic Style" (https://leanpub.com/datastyle/).


* [twitter](https://twitter.com/jtleek)
* [github](https://github.com/jtleek)
* [web](http://jtleek.com/)

__Stephanie Hicks__

Stephanie C. Hicks is an Assistant Professor in the Department of Biostatistics at Johns Hopkins Bloomberg School of Public Health. She develops statistical methods, tools and software for the analysis of genomics data. Her research interests are at the intersection of statistics, genomics, and data science. Broadly, she is focused on two major areas of research: (1) data science education and (2) developing statistical methods, tools and software for the analysis of genomics data to improve quantification and our understanding of biological variability. She taught the major [data science course](http://datasciencelabs.github.io/) at Harvard before joining the faculty at Johns Hopkins. She is also co-creator of the Tidyverse Skills for Data Science in R Specialization on Coursera (https://www.coursera.org/specializations/tidyverse-data-science-r) and founder and lead faculty of the [Open Case Studies](https://www.opencasestudies.org) project funded by the Bloomberg American Health Intiative (https://americanhealth.jhu.edu/open-case-studies). She also is a co-host of [The Corresponding Author](https://twitter.com/CorrespondAuth) podcast and a co-founder and co-organizer of [R-Ladies Baltimore](https://rladies-baltimore.github.io). 

* [twitter](https://twitter.com/stephaniehicks) 
* [github](https://github.com/stephaniehicks)
* [web](http://www.stephaniehicks.com/)


__Roger Peng__ 


Roger D. Peng is a Professor of Biostatistics at the Johns Hopkins Bloomberg School of Public Health. He is also a co-founder of the Johns Hopkins Data Science Specialization, the [Simply Statistics blog](http://simplystatistics.org/) where he writes about statistics for the general public, the [Not So Standard Deviations](http://www.nssdeviations.com) podcast with Hilary Parker, and [The Effort Report](http://effortreport.libsyn.com/) podcast with Elizabeth Matsui. Roger conducts research on developing statistical methods for problems in environmental health. He has made substantial contributions to understanding the health effects of indoor and outdoor air pollution in the U.S. and around the world. He is the recipient of the 2016 Mortimer Spiegelman Award from the American Public Health Association, which honors a statistician who has made outstanding contributions to health statistics.


* [twitter](https://twitter.com/rdpeng) 
* [github](https://github.com/rdpeng)  
* [web](https://rdpeng.org)


 __Brian Caffo__ 
 
Brian Caffo is a Professor in the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health. Along with Roger Peng and Jeff Leek, Dr. Caffo created the Data Science Specialization on Coursera. Dr. Caffo is a leading expert in statistics and biostatistics and is the recipient of the PECASE award, the highest honor given by the US Government for early career scientists and engineers.


* [twitter](https://twitter.com/bcaffo) 
* [github](https://github.com/bcaffo) 
* [web](http://www.bcaffo.com)


__Carrie Wright__

Carrie Wright is an Assistant Scientist in the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health. Dr. Wright's work is focused on innovating ways to make data science and computational biology more accessible to audiences of varied computational experience. She is a member of the [Open Case Studies](https://opencasestudies.github.io/) team and the [Informatics Technology for Cancer Research (ITCR) Training Network (ITN)](https://www.itcrtraining.org/). She also co-created the [Tidyverse Skills for Data Science in R Specialization](https://www.coursera.org/specializations/tidyverse-data-science-r) on Coursera with Stephanie Hicks, Roger Peng, and Shannon Ellis. Prior to joining the Johns Hopkins Data Science Lab, Dr. Wright was a Postdoctoral Fellow at the [Lieber Institute for Brain Development (LIBD)](https://www.libd.org/), where her research focused on uncovering genetic mechanisms (particularly involving non-coding RNA) in psychiatric disease through the utilization of data science tools. At LIBD, she co-founded the [LIBD rstats club](http://research.libd.org/rstatsclub/), a community designed to encourage others to learn more about R programming and statistics. Dr. Wright has also served as an instructor for the [Baltimore Underground Science Space](http://www.bugssonline.org/) and the [Johns Hopkins Center for Talented Youth](https://cty.jhu.edu/).

* [twitter](https://twitter.com/mirnas22)
* [github](https://github.com/carriewright11) 
* [web](https://carriewright11.github.io)

__John Muschelli__

John Muschelli is an Associate Scientist at the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health. He leads the Technology Development team for the CBDS+ program. His work also focuses on processing and analyzing medical images, usually of the brain. He is a member of the [Open Case Studies](https://opencasestudies.github.io/) team and the [Informatics Technology for Cancer Research (ITCR) Training Network (ITN)](https://www.itcrtraining.org/).  He is a lead developer on the [Neuroconductor](https://neuroconductor.org/) and [Osler InHealth](https://oslerinhealth.org/) platforms.  His blog is [A HopStat and Jump Away](https://hopstat.wordpress.com/).  He teaching the open courses of [An Introduction to R](https://johnmuschelli.com/intro_to_r/) and [Imaging in R](https://johnmuschelli.com/imaging_in_r/).

* [twitter](https://twitter.com/strictlystat)
* [github](https://github.com/muschellij2)
* [web](https://johnmuschelli.com/)

__Sarah Wheelan__

Sarah Wheelan is an Associate Professor in the Department of Oncology at the Johns Hopkins University School of Medicine and in the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health. She is one of the founders of the Center for Computational Genomics, an educational initiative that won competitive funding at the university level. With this center she teaches a Practical Genomics Workshop each year and holds a symposium on bioinformatics and computational biology. Her research interests are transposon biology and the 3-dimensional architecture of chromatin in the nucleus. She is a recipient of the Johns Hopkins University Professor’s Award for Teaching Excellence in Biomedical Sciences.

* [github](https://github.com/swheelan)
* [web](http://sjwheelan.som.jhmi.edu/)

__Candace Savonen__

Candace Savonen is a Research Associate in the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health. She creates bioinformatic education materials for cancer genomics, looking for ways to emphasize reproducibility and good data science practices. Her research background is in Neuroscience. 

* [twitter](https://twitter.com/cansavvy)
* [github](https://github.com/cansavvy)
* [web](https://cansavvy.com/)

__Ava Hoffman__

Ava Hoffman is a Research Associate in the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health. She develops resources to make genomics computing tools more accessible to broader audiences. Prior to joining the Johns Hopkins Data Science Lab, Dr. Hoffman researched landscape genomics of weedy plants evolving in cities as a Postdoctoral Fellow in the Johns Hopkins Department of Earth and Planetary Sciences. She also developed data science tools for Fortune 500 companies with a global consulting firm. 

* [twitter](https://twitter.com/avamariehoffman)
* [github](https://github.com/avahoffman)
* [web](https://www.avahoffman.com/)

__Katherine Cox__

Katherine Cox is an Associate Faculty in the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health.  She creates onboarding and training materials for the [AnVIL](https://anvilproject.org/) (Analysis, Visualization, and Informatics Lab-Space) Project.  She is also the director of C-MOOR (Carnegie Massive Open Online Research), where she leads development of cloud-based bioinformatics training and research opportunities.

* [github](https://github.com/KatherineCox)

___

## Staff

__Jessica Crowell__

Jessica is a videographer and editor at Johns Hopkins Bloomberg School of Public Health, Department of Biostatistics.  After graduating with a BFA in Video and Film from MICA (Maryland Institute College of Art), she joined the department in 2015. Since then, Jessica has shot and edited over three hundred MOOCs, a short documentary of the Biostat Dept. and its history, and has also created many other promo videos (sometimes involving puppets or animation). She is driven to maintain a collaborative balance between creativity and academic integrity, working closely with the members of Data Science Lab and members of the faculty to support them in all their endeavors.


__Ira Gooding__

Ira Gooding is Manager of the Open Education Lab in the Center for Teaching and Learning at the Johns Hopkins Bloomberg School of Public Health. He has contributed to the development of more than 50 massive open online courses and specializations, including the Data Science, Executive Data Science, Genomic Data Science Specializations. Ira is also Provost’s Fellow for Digital Initiatives. 

* [twitter (JHOpenEd)](https://twitter.com/JHOpenEdLab)
* [twitter](https://twitter.com/IraGooding)
* [web (Open Ed Lab)](http://www.jhsph.edu/offices-and-services/center-for-teaching-and-learning/our-services/open-education-lab/)


__Ashley Johnson__

Ashley K.G. Johnson is the program administrator for CBDS+ at the Johns Hopkins Bloomberg School of Public Health. She facilitates tutoring for program participants, manages recruitment efforts and the development of corporate and non-profit partnerships. Ashley is a Baltimore native and a graduate of Loyola University Maryland.

__Simone Sawyer__

Simone Sawyer is the Scholar Advocate for CBDS+. She serves as a case manager and professional development coach for current and alumni scholars. By ensuring scholars are connected to wrap-around services and work-place tips, it is the hope that they will succeed both personally and professionally in the data science field.

___

## Affiliates


* [Lucy D'Agostino McGowan](https://www.lucymcgowan.com)
* [Ben Langmead](http://www.langmead-lab.org/)
* [Leah Jager](http://www.jhsph.edu/faculty/directory/profile/2909/leah-r-jager)
* [Steven Salzberg](https://salzberg-lab.org/)
* [James Taylor](http://taylorlab.org/)
* [Mihaela Pertea](http://ccb.jhu.edu/people/mpertea/)
* [Kasper Hansen](http://www.hansenlab.org/)
* [Liliana Florea](http://florealab.org/)
* [Shannon Ellis](http://www.shanellis.com/)



