---
title: "Get your data app built"
---

We run a program at Johns Hopkins where students learn to develop data-focused web and SMS based applications. We are always on the lookout for project ideas that solve real world problems. We generally build apps that are useful for: 

* Data donation - if you have a group of people you would like to donate data to your project. 
* Data collection - if you would like to build an app for collecting data from people. 
* Data visualziation - if you have a data set and would like to have a web app for interacting with the data
* Data interaction - if you have a statistical or machine learning model and you would like a web interface for it. 

But we are interested in any consumer-facing data product that you might be interested in having built. We want you to submit your wildest, most interesting ideas and we'll see if we can get them built for you. 

Whether your goal is to create an app for personal use, to solve a scientific or business problem, or to build a business, you can start with the JHU Prototyping Lab. Please fill out this form and we'll be in touch about getting your app built. 

<!--html_preserve-->
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSe57v_JOhGvAVbsVm5xtwSMuqRDyHPZaWuhHigkkhYiOl7TsA/viewform?embedded=true" width="800" height="600" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
<!--/html_preserve-->