---
title: MOOC-Generator that access Google APIs
output: 
  html_document:
    theme: cosmo
    toc: yes
---

<!--
Heavily inspired by:
https://github.com/tidyverse/tidyverse.org/blob/master/content/google_privacy_policy.md
-->

## Goal of OAuth with MOOC-generator

The goal of the MOOC-generator is to allow users to use `R` packages such as `didactr` to create videos.  The authentication of the MOOC-generator allows users to look for Google Slide decks on their Google Drive account.  Once a slide deck is selected, the contents of the Google Slide can then be downloaded and converted to a set of PNGs, along with any notes on the slides.  The PNGs with the notes can then be combined into a video.  We use the notes with services such as Amazon Polly, Google Language, and Microsoft Bing to synthesize the text into audio (not covered by the MOOC-generator authentication).  The audio is then overlaid on the slides to create the video.  Once the video is located, the `didactr` package allows users to upload these vidoes to their channel using the YouTube API.  Other packages authenticate users in these domains individually, the MOOC-generator allows for authentication in all of these APIs to have a coherent workflow and only one authentication procedure.

We aim to create educational and instructional videos.  You can see example of an output video we have created for Johns Hopkins at https://www.youtube.com/watch?v=W7Wn2CWThVk.  These goals are a part of the Johns Hopkins Data Science Lab (https://jhudatascience.org/) and will be used for courses such as Cloud-Based Data Science (https://leanpub.com/universities/set/jhu/cloud-based-data-science).  No information from the user is stored other than the number of users that are using the application and the API requsts from each user and what is recorded on Google Projects dashboards for all API-based projects.

## Disclaimer and Privacy Policy

Your use of Google APIs with these packages is subject to each API's respective
terms of service. See <https://developers.google.com/terms/>.  The Privacy statement can be seen [here](../google_privacy_policy.html).


